[build]
command = "gulp build"
functions = "functions/"
publish = "dist/"

[dev]
command = "gulp watch"
framework = "#custom"
port = 8888
targetPort = 3000

[[redirects]]
force = true
from = "/"
status = 301
to = "/fr/"
