[build]
command = "npm run build"
publish = "dist/"
functions = "netlify/functions"

[dev]
command = "npm run dev"
framework = "#custom"
port = 8888
targetPort = 3000

[[redirects]]
force = true
from = "/"
status = 301
to = "/fr/"
